export class Kid {
  constructor(name, description, image) {
    this.name = name;
    this.description = description;
    this.image = image;
  }
}

export const Kids = [
  new Kid("William Chavez",
          "Until he was almost 2, William was always sick. Born in March 2004, William suffered chronic respiratory infections, unexplained fevers, reflux and failure to thrive. He looked thin and wane. In December 2004, Sarah Chesrown, MD, Ph.D., a pediatric pulmonologist at Shands Children’s Hospital, diagnosed William with asthma and treated his symptoms aggressively. William’s respiratory health improved, but he still tired easily, became short of breath during activity, and he ate poorly. Three months later, (Tallahassee) physicians found that William had a congenital heart defect called partial anomalous pulmonary venous return (two of his pulmonary veins are attached to the wrong place on his heart).",
          require('../assets/photos/kids/williamchavez.jpg')),
  new Kid("Carson Chapman",
          "In January of 2007, Carson was an active, funny and some might say very mischievous, four year old. So when he came to me in the kitchen one afternoon and said he broke his arm, I brushed him off and said oh you would be in a lot more pain if you really broke your arm. And also being that I am a nurse I don’t tend to get overly excited unless a bone is hanging out or someone is gushing blood. But over the next few days, Carson continued to complain of arm pain. So I decided I should probably take him seriously and get his arm checked out. Through numerous appointments and x-rays, the doctors thought something looked weird around his elbow and it could possibly be a hairline fracture so they decided to put his arm in a cast for two weeks.",
          require('../assets/photos/kids/carsonchapman.jpg')),
  new Kid("Jake Crumpacker",
          "Jake’s leg was in pain for months leading up to February 2011. At night, his dad would rub his leg and give him ibuprofen. The next day, Jake would play two soccer games followed by baseball practice and finish the evening training for track. Still the leg pain made him mom, Barbara, wonder in her son had cancer. She had worked in a cancer unit and knew the signs. But since he would play, run and simply not slow down, Barbara and Jake’s dad, Jon, just attributed it to a strained tendon or muscle. On February 28th, their world would drastically change. That’s when local physicians found a growth on Jake’s fibula that needed to be evaluated immediately by experts.",
          require('../assets/photos/kids/jakecrumpacker.jpg')),
  new Kid("Parker Fox",
          "When Parker was 3 years old, he was diagnosed with a precursor to leukemia called myelodysplastic syndrome. After 28 radiation treatments and 14 days of high dose chemo, he had a bone marrow transplant at Shands Hospital in Gainesville. Today, Parker is in his 14th year of remission! He plays basketball, loves to jump on the trampoline, ride his bike, play Wii Just Dance 3 and tell jokes. Parker is excited to be at his 9th FSU Dance Marathon.",
          require('../assets/photos/kids/parkerFox.png')),
  new Kid("Grayson Irwin",
          "Grayson loves sports and has recently played soccer, t-Ball and is on a Basketball team this fall!  He can easily tell you everything you need to know about Star Wars and can usually be found playing with his Hot Wheels cars and building one with his Lego sets!",
          require('../assets/photos/kids/graysonIrwin1.png')),
  new Kid("Lauren Price",
          "On August 29, 2013, 8 year old Lauren and her family received the heartbreaking news that a tumor found on Lauren's knee was cancer. Lauren was diagnosed with osteosarcoma, and began chemotherapy immediately at Shands Children’s Hospital. Though Lauren and her family were devastated to learn of the cancer, they knew that the doctors and nurses at Shands would do everything to make sure that Lauren got the best treatment.The funds from DM at FSU and CMN have helped Lauren and her family with chemotherapy and treatment during their time at Shands.",
          require('../assets/photos/kids/LaurenPrice1.jpg')),
  new Kid("Jack Murray",
          "His favorite color is green, he plays guitar, very well I think, he likes queso and Chinese food (not together), fav. Movie is Casablanca and tv right now is people of Earth.  He really loves history, has taken civil war class and ww2 currently.  Takes strategy gaming club very seriously and is found gaming online with his friends, when not playing airsoft or guitar.  He also likes fishing but will not tell you that probably.",
          require('../assets/photos/kids/jackMurray1.png')),
  new Kid("Kayla Mills",
          "Kayla was born with severe meconium aspiration.  Meconium aspiration occurs when a baby breathes in amniotic fluid containing meconium (the baby’s first stools).  As a result of the severe meconium aspiration, Kayla also had e-coli, pneumonia and strep.  She was immediately put on a mechanical ventilator (breathing machine) to breathe for her.  In addition, she was medically paralyzed and blindfolded so that she would not be distracted by outside stimuli. Still, her condition continued to worsen and she was life-flighted to Shands Hospital.  While at Shands, her right lung collapsed and she had to have two blood transfusions. Fortunately, her superior medical team had her healthy enough to be transferred back to TMH in record time. Kayla was then released from TMH ten days later. Today, Kayla is a bright, energetic and healthy child.  Thank you Shands Hospital and Children’s Miracle Network!",
          require('../assets/photos/kids/Kayla_Mills.jpg')),
  new Kid("Hunter Newell",
          "I went in for an ultrasound 2 ½ weeks before my due date and the baby was measuring to be 9 lbs 11 ozs.  Since he was measuring to be so large, the midwife decided to induce me the next day.  I went in for an induction and everything seemed fine as it was very similar to my first pregnancy.  Immediately after Hunter was born, the midwife handed him to me to hold.  It only took a couple seconds for us to realize that Hunter was having difficulty breathing as he was gasping for air.  The midwife immediately took Hunter and began to pat on his back to loosen up the fluid they thought was in his lungs.  Unfortunately, this did not help him.  After about 2 minutes, the midwife called down the NICU team to assess Hunter.  They quickly realized that they could not help Hunter and whisked him away to the NICU.",
          require('../assets/photos/kids/HunterNewell1.jpg')),
  new Kid("Alyssa Mann",
          "Biography Coming Soon!",
          require('../assets/photos/kids/alyssamann.jpg')),
  new Kid("Marshal Fisher",
          "“I would say building /creating. Doing things with his hands. After countless hours in hospitals and lying in bed, he's not a tv kid would rather build Legos, Gundams or model kits! And he then recreates/rearranges, sometimes paints etc in his own way puts his own spin on things. He also loves to draw, very artistic, and create with clay !” --Betsy Fisher, Marshal’s Mom",
          require('../assets/photos/kids/marshalFisher.png')),
  new Kid("Jessica Rewiski",
          "Jessica was born 2 months early which caused many health complications. One of those being IVH: interventricular hemorrhage. (Bleeding in the brain. )This caused another condition called Hydrocephalus. Which means that the fluid cycle of cerebral spinal fluid in your brain is blocked. Because of that, her brain started building up too much pressure and she had her first brain surgery When she was 12 months old. The amazing neurosurgeon at Shands Children's Hospital placed a life-saving device in Jessica's brain called a shunt. This device maintains normal pressure in her brain and allows Jessica to live a normal, healthy life.",
          require('../assets/photos/kids/jessicarewiski.jpg')),
  new Kid("Caden Buth",
          "Loves the color red, thinks he has the best roar around (like T-Rex), huge fan of dinosaurs, the Hulk, and anything Cars related. Loves to dance and sing, and talks a lot!!! Favorite foods consist of spaghetti and Cambodian chicken soup.",
          require('../assets/photos/kids/cadenbuth.jpg')),
  new Kid("Ayden Price",
          "Biography Coming Soon!",
          require('../assets/photos/kids/AydenPrice1.jpg')),
  new Kid("Taylor Rooks",
          "Before Taylor was born, doctors noticed an irregular heart rate. After being referred to Shands, doctors detected Taylor had a hole between her left and right ventricles of her heart and transposition of the great arteries. Her left and right ventricles were backwards causing her to have complete heart block. Taylor was born on February 25, 2002 at Shands via C-section and was immediately placed in the NICU III for very close observation. Suffering from a heart rate of only 60 and 3 days old, Taylor underwent surgery to have a pacemaker implanted. Taylor has always kept the doctors on their toes with things not going exactly how they were supposed to go. Between her pacemaker causing an infection that went all the way to her heart to a pacemaker that stopped working within hours of surgery being completed. Taylor has had a total of 2 open heart surgeries and 10 heart surgeries and is on her 7th pacemaker.",
          require('../assets/photos/kids/taylorrooks.jpg')),
  new Kid("Powie Patterson",
          "She is 5 years old and was born with a genetic disorder called Mitochondrial Disease. Powie was initially diagnosed in utero with bilateral clubfeet and abnormalities on her brain and kidneys. Once born, she immediately had feeding problems. Her main health scare came at the age of 2 weeks old. She stopped breathing for the first time for 5+ minutes. We were able to resuscitate her and she was diagnosed with Severe Central Sleep Apnea. At that point, neuromuscular and metabolic diseases became a very real possibility. Hospital stays, surgeries, therapy appointments, more diagnosis became part of our everyday life. When she was 2.5, Mitochondrial disease became the official diagnosis and she began treatment. Her health stabilized to a point and then we moved to Florida. We've been at Shands hospital for almost 2 years and Powie is thriving under her specialist care!",
          require('../assets/photos/kids/powiepatterson.jpg')),
  new Kid("Nate Ferrell",
          "Nate was born with a genetic condition called Mitochondrial Disease, a multi-systemic disease resulting in organ dysfunction, Nate has been a patient of UF Health Shands Children's Hospital since his birth. His 9 pediatric specialists at Shands ensure that Nate can live a fairly normal life despite relying heavily on medical equipment and medications to keep his body functioning properly. Because of his amazing medical team and donations to Children's Miracle Network Hospitals, Nate is an energetic and joyful kid who loves attending school, playing golf and the violin, and hanging out with his Dance Marathon at FSU friends!",
          require('../assets/photos/kids/nate_ferrell2.jpg')),
  new Kid("Ragan Thursby",
          "Ragan Thursby was born with Pitt Hopkins Syndrome, a neurological disorder with about only 400 cases diagnosed in the world. While this disorder may leave Ragan unable to speak with her mouth, her energy and smile can fill the room. Money from Dance Marathon at FSU and Children’s Miracle Network have helped fund research to better understand the complexities of Pitt Hopkins Syndrome. Ragan is a bright and beautiful ten year old girl, who is proving to the world that she is not defined by her disorder but by her spirit. Each day, Ragan conquers the symptoms of Pitt Hopkins Syndrome and your donations have helped to make sure that she can live each day to the fullest.",
          require('../assets/photos/kids/raganthursby.jpg')),
  new Kid("Riley Allen",
          "Riley was born with no issues at birth. He was able to go home while his mother had to stay at TMH. When he was 7 days old (12/19/17), Riley had to go back to the doctor because he was not eating or sleeping as much as he should have been. Dr. Martin said that he needed to go to TMH for further testing. While Riley was in the office, his health began to decline. His parents rushed him to the ER, where they did a spinal tap and was then admitted to the ICU. His heart rate was in the 200’s and the doctors were trying to get it under control. He was then life-flighted to Shands on 12/21/2013 and was immediately put on ECMO. He was eventually able to come off ECMO, but his heart was very sick and was barely pumping. At one point, his ejection fraction was less than 20%. He was put on the Berlin heart pump on 1/21/14. On 3/6/14, they received a call that they found a heart for Riley.",
          require('../assets/photos/kids/rileyallen.png')),
  new Kid("Fletcher Huddleston",
          "Fletcher was diagnosed with cancer the end of February 2017.  We were experiencing all of the feelings and emotions you would expect someone in our situation would; we were simultaneously sad, angry, heartbroken, and had a feeling of being helpless.  The type of cancer that Fletcher was diagnosed with, Burkitt’s, is extremely aggressive.  The cancer cells can double every 24 hours and they were doing a number on our boy.  Fletcher went from being happy and running around with his sister and friends to being in the PICU on a breathing tube and dialysis in a span of one week.  To be honest when you are at that point, it’s hard to envision a positive outcome.Luckily we were at an amazing place, Shands, with an amazing team of nurses, doctors, and other support staff to help is get through that initial shock to both our minds and Fletcher’s fragile body.",
          require('../assets/photos/kids/fletcherhuddleston.png')),
  new Kid("Nicole Myer",
          "“Nicole's favorite hobby is dancing her color is light teal her food is rice and gravy and the fun facts about her is loves the movie Lilo and Stitch, loves cats and the 5 Seconds of Summer band” --Peggy Myer (Nicole’s mom)",
          require('../assets/photos/kids/nicolemyer.png')),
  new Kid("Chloe Novak",
          "Chloe was diagnosed in utero with Turner's Syndrome, and corresponding heart complications, including Hypoplastic Left Heart Syndrome. One week after birth, Chloe underwent a Norwood procedure. When she was 5 months old, Chloe had a Glenn procedure performed to improve her oxygenation. There were many complications involved with this procedure, and it became evident that Chloe needed a new heart.  At around 18 months her condition deteriorated and she eventually  went  into universal organ failure.  Her kidneys stopped working so they had to start dialysis. She was so swollen that fluid started leaking out of her skin and her eyes wouldn't close. Just as we were saying goodbye a miracle happened and we received a call that a heart was available.  Miraculously Chloe was transplanted the day after her 2nd birthday and has been doing amazingly well ever since.",
          require('../assets/photos/kids/chloenovak.png')),
  new Kid("Uzo Otuonye",
          "Uzo likes to play his games on his Xbox 360, ride go karts whether its at fun station or  anywhere, and he likes to watch his favorite Youtuber Roman Atwood. His favorite color is Red His favorite food is Macaroni & Cheese. He likes to swim",
          require('../assets/photos/kids/uzootuonye.png'))
];
